# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claudebox < Formula
  desc "Containerized Claude Code with curated MCP servers"
  homepage "https://github.com/ramseymcgrath/claudebox"
  version "0.4.0"
  license "MIT"

  depends_on "docker" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ramseymcgrath/claudebox/releases/download/v0.4.0/claudebox_darwin_amd64.tar.gz"
      sha256 "91d2d218c061974fc843010662f416ff7639399fa104a322e4fa0d098083c55c"

      define_method(:install) do
        bin.install "claudebox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ramseymcgrath/claudebox/releases/download/v0.4.0/claudebox_darwin_arm64.tar.gz"
      sha256 "1c17b689866434972fd3529b43e37b2418a6f56151b6400e3951bc942efe2084"

      define_method(:install) do
        bin.install "claudebox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ramseymcgrath/claudebox/releases/download/v0.4.0/claudebox_linux_amd64.tar.gz"
      sha256 "d884b958329915568951652b3bc0e070048aaecf1f7f02a1e3ea0f53ce6ce3a8"
      define_method(:install) do
        bin.install "claudebox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ramseymcgrath/claudebox/releases/download/v0.4.0/claudebox_linux_arm64.tar.gz"
      sha256 "7f262f0d9c012522dd211a6388995b3aaa3150f739cafcfefbf85a29f460bda3"
      define_method(:install) do
        bin.install "claudebox"
      end
    end
  end

  test do
    system "#{bin}/claudebox", "version"
  end
end
