# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claudebox < Formula
  desc "Containerized Claude Code with curated MCP servers"
  homepage "https://github.com/ramseymcgrath/claudebox"
  version "0.5.1"
  license "MIT"

  depends_on "docker" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ramseymcgrath/claudebox/releases/download/v0.5.1/claudebox_darwin_amd64.tar.gz"
      sha256 "f325e2c3bd5460601ae12a478bb95d00f56538e5f5af5df0315bd53adfcd754f"

      define_method(:install) do
        bin.install "claudebox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ramseymcgrath/claudebox/releases/download/v0.5.1/claudebox_darwin_arm64.tar.gz"
      sha256 "18196b39f958c3d8f39dff569d990e851b624297b4ec2669e108f050d1191789"

      define_method(:install) do
        bin.install "claudebox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ramseymcgrath/claudebox/releases/download/v0.5.1/claudebox_linux_amd64.tar.gz"
      sha256 "9d51286d0a7bcc79ee7a2f1b080db3ad93662735477d31280e5fbcb2b4c7a335"
      define_method(:install) do
        bin.install "claudebox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ramseymcgrath/claudebox/releases/download/v0.5.1/claudebox_linux_arm64.tar.gz"
      sha256 "f6fd7a0a402bb7f421e4f4ec7a0da4ddf5e7005e1bd0198316d03215e11b9c4a"
      define_method(:install) do
        bin.install "claudebox"
      end
    end
  end

  test do
    system "#{bin}/claudebox", "version"
  end
end
